### ISSUE TITLE
How to create jar files instead of AMP

### ISSUE THREAD

**Issue by purohitsumit** [jpotts/share-site-creators#10]
Hi, 
I am new to AMP and alfresco share customization. I am trying to use this plugin with alfresco 4.2.c
I use different tomcat for alfresco and share and I have created some extenions jar files and added it to tomcat/alfresco and tomcat_share/share 
Is there a way to create jar file instead of AMP and add it to tomcat/alfresco/WEB-INF/lib and tomcat_share/share/WEB-INF/lib

thanks
sumit

**Comment by jpotts** [comment]
This project is set up to build AMPs, which is the preferred mechanism for extending Alfresco 4.2.x. You should reorganize your extension to use AMPs as well. But if that's not something you want to do, you can always deploy this extension alongside yours and it should work.

Also, 4.2.c is not a good release for running on production. If you can, upgrade to 4.2.f, or, even better 5.0.d.
