### ISSUE TITLE
HOW TO CREATE AMP FILE FROM SHARE-SITE -CREATORS-REP & SHARE

### ISSUE THREAD

**Issue by zehra2** [jpotts/share-site-creators#11]
HOW TO GENERATE AMP FILE FROM share-site-creators-repo

**Comment by jpotts** [comment]
If you are running 5.0.d please download the AMPs from the releases page. If you would like to build the AMPs from source, follow the instructions in the readme. If you are not familiar with the Alfresco Maven SDK, see this tutorial: http://ecmarchitect.com/alfresco-developer-series-tutorials/maven-sdk/tutorial/tutorial.html
