### ISSUE TITLE
Using addon for 5.1

### ISSUE THREAD

**Issue by ESWBitto** [jpotts/share-site-creators#12]
Will the 5.0 branch work for the upcoming 5.1 CE version of alfresco?

**Comment by jpotts** [comment]
I haven't personally tested it against 5.1 CE yet.

**Comment by marciofoz** [comment]
Work fine with CE 5.1. I use Maven 3.3.9 to install.

**Comment by jpotts** [comment]
Cool, thanks for confirming.
