### ISSUE TITLE
Configure the extension module to be deployed automaticaly

### ISSUE THREAD

**Issue by douglascrp** [jpotts/share-site-creators#16]
Any special reason for the extension module not to be deployed automatically?

**Comment by jpotts** [comment]
No, there is no special reason. It's probably friendlier to end-users to deploy it automatically.

**Comment by douglascrp** [comment]
I have changed this but I don't know how to pull request only this commit
https://github.com/jpotts/share-site-creators/commit/2b50b0da415da70c3b22b346e4600fc37cc41d86

**Comment by douglascrp** [comment]
@jpotts Can you change this?

**Comment by jpotts** [comment]
Done.
