### ISSUE TITLE
Bootstrap causes exception on 5.1

### ISSUE THREAD

**Issue by jpotts** [jpotts/share-site-creators#18]
The new bootstrap context that creates the site creators group on startup after installing the module throws a fatal exception in 5.1 that prevents the server from starting up. The problem is that the version.schema property is not being read from the Alfresco props file for some reason. This works fine in 5.0.x, however.

The exception is:
org.springframework.beans.MethodInvocationException: Property 'targetSchema' threw exception; nested exception is java.lang.IllegalArgumentException: 'targetSchema' must be greater than 'fixesToSchema'

**Comment by goutnet** [comment]
is there any workaround to deactivate the bootstrap and create the group manually for now on community edition (5.1)?

**Comment by goutnet** [comment]
I tried using the -force option on apply_amps script, then creating the group after activating the module.

It works on my test site.
