### ISSUE TITLE
Error with 5.0.d

### ISSUE THREAD

**Issue by marciofoz** [jpotts/share-site-creators#2]
I do a clean install of Alfresco 5.0.d, Maven 3.3.1, Java 1.7..  All worked fine until I installed the amps.  Now I cant access Alfresco and deploy page.  I enter user/password and cant continue.  See the log fragment:

2015-03-29 17:47:20,502  ERROR [web.context.ContextLoader] [localhost-startStop-2] Context initialization failed
 org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:alfresco/application-context.xml]
Offending resource: ServletContext resource [/WEB-INF/web-application-context.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath*:alfresco/module-context.xml]
Offending resource: class path resource [alfresco/application-context.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath*:alfresco/module/*/module-context.xml]
Offending resource: URL [jar:file:/opt/alfresco-5.0.d/tomcat/webapps/alfresco/WEB-INF/lib/alfresco-repository-5.0.d.jar!/alfresco/module-context.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:alfresco/module/share-site-creators-repo/context/service-context.xml]
Offending resource: file [/opt/alfresco-5.0.d/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/share-site-creators-repo/module-context.xml]; nested exception is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 64 in XML document from class path resource [alfresco/module/share-site-creators-repo/context/service-context.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 64; columnNumber: 9; An element with the identifier "accessDecisionManager" must appear in the document.
        at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68)
        at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
        at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:76)

**Comment by jpotts** [comment]
Fixed and committed to the 5.0.d branch.
