### ISSUE TITLE
How about removing the SNAPSHOT from the project version?

### ISSUE THREAD

**Issue by douglascrp** [jpotts/share-site-creators#21]
Don't you think this addon is mature enough to lose the SNAPSHOT from its version?

**Comment by jpotts** [comment]
Probably. I haven't given it much thought.

On Thu, Jun 2, 2016 at 6:00 PM, Douglas C. R. Paes <notifications@github.com

**Comment by jpotts** [comment]
Done, the new release 0.0.3 has no SNAPSHOT designation.
