### ISSUE TITLE
Share site creator -hide createSite menu

### ISSUE THREAD

**Issue by jayaseelanmuthu** [jpotts/share-site-creators#27]
Hi Potts,
I have installed 5.1 enterprise edition on my PC and downloaded the share-site-creator project and imported into my eclipse. But i was not able to build the project,

[ERROR]   The project com.metaversant1:share-site-creators-share:0.0.5 (C:\Users
\xbblm9i\Downloads\share-site-creators-0.0.5\share-site-creators-0.0.5\share-sit
e-creators-share\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.alfresco.surf:spring-surf-
api:jar must be a valid version but is '${dependency.surf.version}'. @ com.metav
ersant1:share-site-creators-share:[unknown-version], C:\Users\xbblm9i\Downloads\
share-site-creators-0.0.5\share-site-creators-0.0.5\share-site-creators-share\po
m.xml, line 70, column 14

please advise.

**Comment by jpotts** [comment]
See the "Manual Installation" section in https://github.com/jpotts/share-site-creators/blob/master/readme.md. You must specify the Surf version when building.

**Comment by jayaseelanmuthu** [comment]
Thanks for that

**Comment by jayaseelanmuthu** [comment]
We have a requirement that we need  to send the encrypted userId and Password to the Login webscript to get the alf ticket. (instead of plain userId and password). We need to extend the login webscript for this.
Can you please advise me on this? what is the class that i have to extend or override?
