### ISSUE TITLE
Extending login webscript to accept the encrypted password & userid

### ISSUE THREAD

**Issue by jayaseelanmuthu** [jpotts/share-site-creators#28]
Hi Potts,
We have a requirement that we need to send the encrypted userId and Password to the Login webscript to get the alf ticket. (instead of plain userId and password). We need to extend the login webscript for this.
Can you please advise me on this? what is the class that i have to extend or override?

**Comment by jpotts** [comment]
This is not related to share-site-creators. You should post something on the [Alfresco forums](http://community.alfresco.com).

**Comment by jayaseelanmuthu** [comment]
Thank you
