### ISSUE TITLE
Issue with 5.0.d 

### ISSUE THREAD

**Issue by marciofoz** [jpotts/share-site-creators#3]
I made the changes and now I can access the deploy menu and Alfresco share, but still not showing the `create site` same with admin user in Group_Site_Creators.

More any changes/tests I can do here ?
Regards.

![captura de tela 2015-03-30 as 10 40 53](https://cloud.githubusercontent.com/assets/10158758/6897431/008085ea-d6ca-11e4-872e-730049b9169d.png)
![captura de tela 2015-03-30 as 10 41 50](https://cloud.githubusercontent.com/assets/10158758/6897435/03b29302-d6ca-11e4-8b47-d3a7492cb269.png)

**Comment by jpotts** [comment]
Take GROUP_ off of your group. alfresco will add that automatically.

Jeff

**Comment by marciofoz** [comment]
Worked :)
Tks
