### ISSUE TITLE
Duplicate group created

### ISSUE THREAD

**Issue by jason6asher** [jpotts/share-site-creators#34]
SITE_CREATORS group already existed which resulted in a duplicate being created. After deleting both and recreating the group, the create site is unavailable whether or not the user is in the new group

**Comment by jpotts** [comment]
What steps did you take to cause the duplicate group? Did you uninstall and reinstall the module? If you uninstall you must delete that group before you install again. If Alfresco thinks the module has never been installed and then tries to install it, it is going to try to create the group, as you've seen.

The last part of your issue should really be treated separately. If the group has been created properly, preferably by the bootstrap, then everything should work. If you've logged out and logged back in as a user in SITE_CREATORS and still don't see create site, please file a separate ticket.

**Comment by jpotts** [comment]
I cannot recreate this so I'm marking it invalid. If you can reproduce with the latest version of the module running on Alfresco 5.2, please re-open with the steps to reproduce.
