### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by awmpas** [jpotts/share-site-creators#36]
This module is really cool. Thanks.
Why not manage rights on the delete site link (in the my-sites and site-search dashlets) with the SITES_CREATORS group ?

**Comment by douglascrp** [comment]
What do you mean by that?
By default, only site managers are allowed to delete sites. http://docs.alfresco.com/community/tasks/sites-delete.html
Isn't that enough?

**Comment by awmpas** [comment]
Sorry for the response time.
It can be convenient to manage creation rights through a group.
Just for those who could be interested in this option, I managed to overload the "RenderCellActions" in the dashlet my-site to take into account this notion of group with this code : 

```
var createSiteLink = Dom.get(this.id + "-createSite-button");
if (createSiteLink){
             desc += '<a class="delete-site ' + DELETE_EVENTCLASS + '" title="' + this.msg("link.deleteSite") + '">&nbsp;</a>';
 }
```
I started from this tutorial [https://docs.alfresco.com/5.2/tasks/dev-extensions-share-tutorials-customizing-widget-instantiation.html](url)

But I have trouble on the site-finder part. I can't overload in the same way the RenderCellActions.
Do you have an idea to handle this case?
