### ISSUE TITLE
5.0.d no create site link even when in GROUP_SITE_CREATORS group

### ISSUE THREAD

**Issue by digcat** [jpotts/share-site-creators#4]
Hi Jeff
Have been interested in your module, and have been playing with it.  i can see the site prevention is now working in 5.0.d, when no user is in the group.  However, I'm also finding even with the admin user/or admin group in the GROUP_SITE_CREATORS group, I'm not seeing the create site link anywhere?  just thought I'd give you feedback, cheers for your efforts.

regards
Daren

testing on your module  
https://github.com/digcat/alfresco-tests/blob/master/test_share_site_creators.py

**Comment by jpotts** [comment]
This is working fine for me and others in 5.0.d. Can you send me a screenshot of your group browser?

Jeff

**Comment by digcat** [comment]
Hi Jeff

Ok, here are screen shots, showing the group is created, but the create 
site link is not showing in the menu.  The amp applied cleanly using 
bin/apply_amps.sh, and appeared in share deploy area fine.  And, after 
enabling the addon, then disabling the addon, I can see the create site 
link reappears.

I tried adding the ALFRESCO_ADMINISTRATORS group to the 
GROUP_SITE_CREATORS group, as well trying the admin user.
The records management amps are installed, don't see why that has any 
relevance, but Id mention in case.

Ill build into puppet, so install the amp at creation time, and see if 
that makes any difference.

cheers for your time, regards
Daren

**Comment by jpotts** [comment]
I don't see any screenshots, but just to clarify: The group should be named "SITE_CREATORS". Alfresco will prepend the group name with "GROUP_". You should not specify that part.

**Comment by digcat** [comment]
Hi Jeff

Hmm, seems github strips the attachments, Ill try embedding see if that 
helps.  Hopefully these make their way to you.
So thanks for the clarification on the group name, i had indeed used 
GROUP_SITE_CREATORS.  Anyway, having now used SITE_CREATORS, 
unfortunately Im still not seeing the Create Site, for the admin user 
even when admin is in the group.
Im wondering if my issue is due to other addons already installed. Ill 
get some other folks to test this end with the build.  I'm applying your 
addon after the build is up, but it looks like its applied ok.  Anyway, 
thanks again for your time in this matter, will feed back more when I 
have it.

many thanks, Daren


Our list of addons installed are:

Module 'org_alfresco_module_rm' installed in 
'/opt/alfresco/tomcat/webapps/alfresco.war'
    -    Title:        Records Management (2.3.c)
    -    Version:      2.3
    -    Install Date: Tue Apr 07 05:47:28 UTC 2015
    -    Description:   Alfresco Record Management Extension
Module 'share-site-creators-repo' installed in 
'/opt/alfresco/tomcat/webapps/alfresco.war'
    -    Title:        share-site-creators-repo AMP project
    -    Version:      0.0.2.1504031720
    -    Install Date: Tue Apr 07 05:47:23 UTC 2015
    -    Description:   Changes the permissions so that only members of 
a specific group can create sites.
Module 'org.alfresco.integrations.google.docs' installed in 
'/opt/alfresco/tomcat/webapps/alfresco.war'
    -    Title:        Alfresco / Google Docs Integration
    -    Version:      3.0.0
    -    Install Date: Tue Apr 07 05:47:21 UTC 2015
    -    Description:   The Repository side artifacts of the Alfresco / 
Google Docs Integration.
Module 'de.fme.alfresco.JavascriptConsole-repo' installed in 
'/opt/alfresco/tomcat/webapps/alfresco.war'
    -    Title:        fme Javascript Console Repository Extension
    -    Version:      0.5
    -    Install Date: Tue Apr 07 05:47:19 UTC 2015
    -    Description:   Adminstration console module to execute 
arbitrary javascript code.
Module 'org.alfresco.module.vti' installed in 
'/opt/alfresco/tomcat/webapps/alfresco.war'
    -    Title:        Vti
    -    Version:      1.3
    -    Install Date: Tue Apr 07 05:47:16 UTC 2015
    -    Description:   Alfresco Vti Extension, provides Sharepoint protocol
Module 'uploader-plus-repo' installed in 
'/opt/alfresco/tomcat/webapps/alfresco.war'
    -    Title:        uploader-plus-repo
    -    Version:      1.2.1502120927
    -    Install Date: Tue Apr 07 05:47:13 UTC 2015
    -    Description:   uploader-plus AMP for Alfresco repository 4.2.x 
and 5.0.x
Module 'share-site-creators-share' installed in 
'/opt/alfresco/tomcat/webapps/share.war'
    -    Title:        share-site-creators-share AMP project
    -    Version:      0.0.2.1504031721
    -    Install Date: Tue Apr 07 05:47:54 UTC 2015
    -    Description:   Hides all "create site" links from all users 
except those belonging to a specific group.
Module 'de.fme.alfresco.JavascriptConsole-share' installed in 
'/opt/alfresco/tomcat/webapps/share.war'
    -    Title:        fme Javascript Console Share Extension
    -    Version:      0.5
    -    Install Date: Tue Apr 07 05:47:51 UTC 2015
    -    Description:   Adminstration console module to execute 
arbitrary javascript code.
Module 'org.alfresco.integrations.share.google.docs' installed in 
'/opt/alfresco/tomcat/webapps/share.war'
    -    Title:        Alfresco / Google Docs Share Module
    -    Version:      3.0.0
    -    Install Date: Tue Apr 07 05:47:47 UTC 2015
    -    Description:   The Share side artifacts of the Alfresco / 
Google Docs Integration.
Module 'org_alfresco_module_rm_share' installed in 
'/opt/alfresco/tomcat/webapps/share.war'
    -    Title:        Alfresco Record Management Share Extension (2.3.c)
    -    Version:      2.3
    -    Install Date: Tue Apr 07 05:47:44 UTC 2015
    -    Description:   Alfresco Record Management Share Extension
Module 'libreoffice-online-edit-share' installed in 
'/opt/alfresco/tomcat/webapps/share.war'
    -    Title:        Alfresco Share Module for LibreOffice Edit Online 
functionality
    -    Version:      1.2.3
    -    Install Date: Tue Apr 07 05:47:38 UTC 2015
    -    Description:   Alfresco Share Module for LibreOffice Edit 
Online functionality
Module 'uploader-plus-surf' installed in 
'/opt/alfresco/tomcat/webapps/share.war'
    -    Title:        uploader-plus-surf
    -    Version:      1.2.1502120927
    -    Install Date: Tue Apr 07 05:47:33 UTC 2015
    -    Description:   uploader-plus AMP using the Surf framework for 
Share 4.2.x and

**Comment by digcat** [comment]
Hi Jeff,

Ok, so might a restart be needed?  I'm now seeing the create site, after 
I restarted.  But yes I'm seeing the Create site once the user is in the 
SITE_CREATORS group yay !!,  Ill close the issue, thanks for your attention,

regards

Daren

**Comment by digcat** [comment]
Hi Jeff

Ok, so have it working perfectly, once i logoff the session, so a 
restart isnt needed, but I hadnt logged the session out, and backin.  
Once I do that, the create site link reappears, when the user is in the 
SITE_CREATORS group.

many thanks, sorry for the noise :)

regards

Daren
