### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by marciofoz** [jpotts/share-site-creators#5]
Hello..
When I execute 'run.sh' at share-site-creators-repo I got:

Downloading: https://repo.maven.apache.org/maven2/org/alfresco/alfresco-platform-distribution/5.0.d/alfresco-platform-distribution-5.0.d.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.0.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: clojurewerkz:neocons:jar:3.0.0, cheshire:cheshire:jar:5.3.1, tigris:tigris:jar:0.1.1, clj-http:clj-http:jar:0.9.1, slingshot:slingshot:jar:0.10.3, crouton:crouton:jar:0.1.1, potemkin:potemkin:jar:0.3.4, clj-tuple:clj-tuple:jar:0.1.2, riddley:riddley:jar:0.1.6, clojurewerkz:support:jar:0.20.0, clojurewerkz:urly:jar:2.0.0-alpha5, org.flatland:useful:jar:0.10.6, jansi-clj:jansi-clj:jar:0.1.0, io.aviso:pretty:jar:0.1.12, org.clojars.pmonks:depends:jar:0.3.0, org.clojars.pmonks:multigrep:jar:0.2.0, org.clojars.pmonks:bookmark-writer:jar:0.1.0, org.clojars.pmonks:spinner:jar:0.2.0: Could not transfer artifact clojurewerkz:neocons:jar:3.0.0 from/to sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots): oss.sonatype.org @ 
[ERROR] Unknown packaging: amp @ line 9, column 16
[ERROR] Non-resolvable import POM: Could not transfer artifact org.alfresco:alfresco-platform-distribution:pom:5.0.d from/to alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public): artifacts.alfresco.com: unknown error @ line 59, column 25
[ERROR] 'dependencies.dependency.version' for org.alfresco:alfresco-repository:jar is missing. @ line 72, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.ecmarchitect:share-site-creators-repo:0.0.2-SNAPSHOT (/root/share-site-creators-5.0.d/share-site-creators-repo/pom.xml) has 4 errors
[ERROR]     Unresolveable build extension: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.0.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: clojurewerkz:neocons:jar:3.0.0, cheshire:cheshire:jar:5.3.1, tigris:tigris:jar:0.1.1, clj-http:clj-http:jar:0.9.1, slingshot:slingshot:jar:0.10.3, crouton:crouton:jar:0.1.1, potemkin:potemkin:jar:0.3.4, clj-tuple:clj-tuple:jar:0.1.2, riddley:riddley:jar:0.1.6, clojurewerkz:support:jar:0.20.0, clojurewerkz:urly:jar:2.0.0-alpha5, org.flatland:useful:jar:0.10.6, jansi-clj:jansi-clj:jar:0.1.0, io.aviso:pretty:jar:0.1.12, org.clojars.pmonks:depends:jar:0.3.0, org.clojars.pmonks:multigrep:jar:0.2.0, org.clojars.pmonks:bookmark-writer:jar:0.1.0, org.clojars.pmonks:spinner:jar:0.2.0: Could not transfer artifact clojurewerkz:neocons:jar:3.0.0 from/to sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots): oss.sonatype.org: Unknown host oss.sonatype.org -> [Help 2]
[ERROR]     Unknown packaging: amp @ line 9, column 16
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.alfresco:alfresco-platform-distribution:pom:5.0.d from/to alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public): artifacts.alfresco.com: unknown error @ line 59, column 25: Unknown host artifacts.alfresco.com: unknown error -> [Help 3]
[ERROR]     'dependencies.dependency.version' for org.alfresco:alfresco-repository:jar is missing. @ line 72, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:

my maven settings: 
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T17:10:27-03:00)
Maven home: /usr/local/apache-maven-3.3.1
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /opt/alfresco-5.0.d/java
Default locale: pt_BR, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-229.1.2.el7.x86_64", arch: "amd64", family: "unix"

Whats missing ?

Thanks in advance.

**Comment by jpotts** [comment]
Can you run mvn clean install and see if that completes successfully?
