### ISSUE TITLE
Permanent change

### ISSUE THREAD

**Issue by 4lfr3d7115** [jpotts/share-site-creators#7]
Each time I restart alfresco, I have to deployment again the module. How leave permanent change ?

**Comment by jpotts** [comment]
Edit https://github.com/jpotts/share-site-creators/blob/master/share-site-creators-share/src/main/amp/config/alfresco/web-extension/site-data/site-creators-module-extension.xml and change auto deploy to true. Then, re-build the Share AMP and re-deploy.
