### ISSUE TITLE
Error creating Amp file

### ISSUE THREAD

**Issue by ESWBitto** [jpotts/share-site-creators#8]
Hey Jeff,

When creating the amp file downloading content from

 http://repo.maven.apache.org/maven2/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.jar

I can't build the amp file. I think this is a dead link

**Comment by douglascrp** [comment]
@ESWBitto it must be something wrong with your maven setup.
I've just downloaded the source code and I was able to compile it without any project.

**Comment by jpotts** [comment]
I've done a mvn dependency:list on both the repo and share project and neither one depend on that JAR.
